version: '3.7'

services:
  grafana:
    image: grafana/grafana:latest
    ports:
      - '3000:3000'
    environment:
      GF_RENDERING_SERVER_URL: http://renderer:8081/render
      GF_RENDERING_CALLBACK_URL: http://grafana:3000/
      GF_LOG_FILTERS: rendering:debug
    networks:
      - grafana-network

  renderer:
    image: grafana/grafana-image-renderer:latest
    ports:
      - '8081:8081'
    environment:
      RENDERING_MODE: clustered
      RENDERING_CLUSTERING_MODE: context
      RENDERING_CLUSTERING_MAX_CONCURRENCY: 10
      RENDERING_CLUSTERING_TIMEOUT: 30
    networks:
      - grafana-network

  grafana-pdf-reporter:
    build: .
    ports:
      - '9090:9090'
    networks:
      - grafana-network

networks:
  grafana-network:
    driver: bridge
